/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/visualPanel.java to edit this template
 */
package org.ide.wizard.packages;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import org.netbeans.api.project.Project;
import org.netbeans.api.project.ui.OpenProjects;

public final class NewPackageVisualPanel1 extends JPanel {

    /**
     * Creates new form NewPackageVisualPanel1
     */
    public NewPackageVisualPanel1() {
        initComponents();
        
        proyectosComboBox.setModel(new DefaultComboBoxModel<>(getListOpenProjects()));
    }

    @Override
    public String getName() {
        return "Paso #1";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proyectosComboBox = new javax.swing.JComboBox<>();
        avisoLabel = new javax.swing.JLabel();
        packageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        introduccionLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(avisoLabel, org.openide.util.NbBundle.getMessage(NewPackageVisualPanel1.class, "NewPackageVisualPanel1.avisoLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(packageLabel, org.openide.util.NbBundle.getMessage(NewPackageVisualPanel1.class, "NewPackageVisualPanel1.packageLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NewPackageVisualPanel1.class, "NewPackageVisualPanel1.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(introduccionLabel, org.openide.util.NbBundle.getMessage(NewPackageVisualPanel1.class, "NewPackageVisualPanel1.introduccionLabel.text")); // NOI18N

        nameField.setText(org.openide.util.NbBundle.getMessage(NewPackageVisualPanel1.class, "NewPackageVisualPanel1.nameField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(introduccionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(packageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proyectosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(introduccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(proyectosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(avisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JLabel introduccionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel packageLabel;
    private javax.swing.JComboBox<String> proyectosComboBox;
    // End of variables declaration//GEN-END:variables

    private String[] getListOpenProjects(){
        Project[] open = OpenProjects.getDefault().getOpenProjects();

        String[] names = new String[open.length];
        for (int i = 0; i < open.length; i++) {
            names[i] = open[i].getProjectDirectory().getNameExt();
        }

        return names;
    }
    
    public Project getProyecto(){
        Project[] open = OpenProjects.getDefault().getOpenProjects();

        String[] names = getListOpenProjects();

        Object sel = proyectosComboBox.getSelectedItem();

        int idx = -1;
        for (int i = 0; i < names.length; i++) {
            if (names[i].equals(sel)) {
                idx = i; break;
            }
        }
        Project proyecto = open[idx];
        System.out.println("Proyecto seleccionada: " + proyecto.getProjectDirectory());
        return proyecto;
    }
    
    public String getNombre(){        
        return nameField.getText();
    }
}
