package org.ide.ia.chat;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top Component encargado del Chat con IA Qwuen 2.5
 *
 * @author Antonio Manuel Guisado Valle
 * @version 1.0
 */
@ConvertAsProperties(
        dtd = "-//org.ide.ia.chat//ChatWindow//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ChatWindowTopComponent",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "properties", openAtStartup = true)
@ActionID(category = "Window", id = "org.ide.ia.chat.ChatWindowTopComponent")
@ActionReference(path = "Menu/Window", position = 2)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ChatWindowAction",
        preferredID = "ChatWindowTopComponent"
)
@Messages({
    "CTL_ChatWindowAction=Chat IA",
    "CTL_ChatWindowTopComponent=Chat IA",
    "HINT_ChatWindowTopComponent=Chat potenciado con IA Qwen 2.5"
})
public final class ChatWindowTopComponent extends TopComponent {

    public ChatWindowTopComponent() {
        initComponents();
        setName(Bundle.CTL_ChatWindowTopComponent());
        setToolTipText(Bundle.HINT_ChatWindowTopComponent());

        sendButton.addActionListener(e -> sendMessage());
        textFieldInput.addActionListener(e -> sendMessage());

        String placeholder = "Preguntar/Responder a Qwen...";
        textFieldInput.setText(placeholder);
        textFieldInput.setText(placeholder);

        textFieldInput.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textFieldInput.getText().equals(placeholder)) {
                    textFieldInput.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textFieldInput.getText().isEmpty()) {
                    textFieldInput.setText(placeholder);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane(chatTextArea,
            jScrollPane1.VERTICAL_SCROLLBAR_AS_NEEDED,
            jScrollPane1.HORIZONTAL_SCROLLBAR_NEVER);
        chatTextArea = new javax.swing.JTextArea();
        textFieldInput = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();

        chatTextArea.setEditable(false);
        chatTextArea.setColumns(20);
        chatTextArea.setLineWrap(true);
        chatTextArea.setRows(5);
        chatTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(chatTextArea);

        textFieldInput.setText(org.openide.util.NbBundle.getMessage(ChatWindowTopComponent.class, "ChatWindowTopComponent.textFieldInput.text")); // NOI18N
        textFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldInputActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(sendButton, org.openide.util.NbBundle.getMessage(ChatWindowTopComponent.class, "ChatWindowTopComponent.sendButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFieldInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldInputActionPerformed
    }//GEN-LAST:event_textFieldInputActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField textFieldInput;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }

    private void sendMessage() {
        String userInput = textFieldInput.getText().trim();

        if (userInput.isEmpty()) {
            return;
        }

        chatTextArea.append("Tú: " + userInput + "\n\n");
        textFieldInput.setText("");
        mostrarAnimacionEspera();

        new Thread(() -> {
            try {
                String response = askOllama(userInput);
                SwingUtilities.invokeLater(() -> {
                    ocultarAnimacionEspera();
                    chatTextArea.append("Qwen: " + formatearTextoPlano(response) + "\n\n");
                });
            } catch (Exception ex) {
                SwingUtilities.invokeLater(() -> {
                    ocultarAnimacionEspera();
                    chatTextArea.append("Error: " + ex.getMessage() + "\n\n");
                });
            }
        }).start();
    }

    private String askOllama(String prompt) throws IOException, org.json.simple.parser.ParseException {
        JSONObject json = new JSONObject();
        json.put("model", "qwen2.5-coder:latest");
        json.put("system", "Eres Qwen, y ayudaras a programadores principiantes Java");
        json.put("prompt", prompt);
        json.put("stream", false);

        URL url = new URL(IAConfig.getOllamaUrl());
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setDoOutput(true);
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");

        if (IAConfig.isRemote()) {
            conn.setRequestProperty("Authorization", "Bearer " + IAConfig.getToken());
        }

        try (OutputStream os = conn.getOutputStream()) {
            os.write(json.toJSONString().getBytes(StandardCharsets.UTF_8));
        }

        if (conn.getResponseCode() != HttpURLConnection.HTTP_OK) {
            throw new IOException("Error al contactar Ollama: " + conn.getResponseCode());
        }

        try (InputStream is = conn.getInputStream()) {
            String responseBody = new String(is.readAllBytes(), StandardCharsets.UTF_8);
            JSONParser parser = new JSONParser();
            JSONObject responseJson = (JSONObject) parser.parse(responseBody);
            String rawResponse = (String) responseJson.get("response");
            return rawResponse != null ? rawResponse.replace("\\n", "\n") : "";
        }
    }

    private Timer animacionTimer;
    private String baseTextoAnimacion = "Esperando respuesta";

    private void mostrarAnimacionEspera() {
        animacionTimer = new Timer(500, new ActionListener() {
            int puntos = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                puntos = (puntos + 1) % 4;
                String dots = ".".repeat(puntos);
                String nuevaLinea = baseTextoAnimacion + dots;

                // Reemplaza la última línea del chat
                String[] lineas = chatTextArea.getText().split("\n");
                lineas[lineas.length - 1] = nuevaLinea;
                chatTextArea.setText(String.join("\n", lineas));
            }
        });

        // Añade línea inicial antes de empezar
        chatTextArea.append(baseTextoAnimacion + "\n");
        animacionTimer.start();
    }

    private void ocultarAnimacionEspera() {
        if (animacionTimer != null && animacionTimer.isRunning()) {
            animacionTimer.stop();
        }

        String[] lineas = chatTextArea.getText().split("\n");
        if (lineas.length > 0 && lineas[lineas.length - 1].startsWith(baseTextoAnimacion)) {
            chatTextArea.setText(String.join("\n", Arrays.copyOf(lineas, lineas.length - 1)));
        }
    }

    private String formatearTextoPlano(String textoMarkdown) {
        StringBuilder resultado = new StringBuilder();
        String[] lineas = textoMarkdown.split("\n");
        boolean enBloquecodigo = false;

        for (int i = 0; i < lineas.length; i++) {
            String linea = lineas[i];

            // Detectar inicio/fin de bloque de código
            if (linea.trim().startsWith("```")) {
                if (!enBloquecodigo) {
                    // Inicio del bloque
                    resultado.append("\n┌─── CÓDIGO ───────────────────────\n");
                    enBloquecodigo = true;
                } else {
                    // Final del bloque
                    resultado.append("└─────────────────────────────────\n\n");
                    enBloquecodigo = false;
                }
                continue; // No agregar la línea ```
            }

            if (enBloquecodigo) {
                resultado.append(linea).append("\n");
            } else {
                String lineaTrimmed = linea.trim();

                if (lineaTrimmed.startsWith("### ")) {
                    resultado.append("\n═══ ").append(lineaTrimmed.substring(4).toUpperCase()).append(" ═══\n");
                } else if (lineaTrimmed.startsWith("## ")) {
                    resultado.append("\n▓▓▓ ").append(lineaTrimmed.substring(3).toUpperCase()).append(" ▓▓▓\n");
                } else if (lineaTrimmed.startsWith("- ")) {
                    resultado.append("  • ").append(formatearLinea(lineaTrimmed.substring(2))).append("\n");
                } else if (!lineaTrimmed.isEmpty()) {
                    resultado.append(formatearLinea(lineaTrimmed)).append("\n");
                } else {
                    resultado.append("\n");
                }
            }
        }

        return resultado.toString();
    }

    private String formatearLinea(String texto) {
        texto = texto.replaceAll("\\*\\*(.*?)\\*\\*", "■$1■");
        texto = texto.replaceAll("\\*(.*?)\\*", "»$1«");
        texto = texto.replaceAll("`(.*?)`", "[$1]");
        return texto;
    }

}
