package org.ide.output;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities; 

/**
 * Top Component encargado de la consola y salida de texto del IDE.
 *
 * @author Antonio Manuel Guisado Valle
 * @version 1.1
 */
@ConvertAsProperties(
        dtd = "-//org.ide.output//Consola//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ConsolaTopComponent",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "org.ide.output.ConsolaTopComponent")
@ActionReference(path = "Menu/Window", position = 3)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ConsolaAction",
        preferredID = "ConsolaTopComponent"
)
@Messages({
    "CTL_ConsolaAction=Consola",
    "CTL_ConsolaTopComponent=Consola",
    "HINT_ConsolaTopComponent=Consola para ver los outputs e introducir inputs"
})
public final class ConsolaTopComponent extends TopComponent {

    private TextAreaInputStream taInputStream;

    public ConsolaTopComponent() {
        initComponents();
        configureSmoothScroll();

        // Salida estandar
        TextAreaOutputStream taOutputStream = new TextAreaOutputStream(consoleTextPane, "IDE");
        PrintStream printStream = new PrintStream(taOutputStream, true, StandardCharsets.UTF_8);
        System.setOut(printStream);
        System.setErr(printStream);

        // Entrada estandar
        taInputStream = new TextAreaInputStream();
        System.setIn(taInputStream); // ¡Esta línea faltaba!

        setDisplayName("Consola IDE");

        // Acción al presionar Enter en el campo de entrada
        textFieldInput.addActionListener(e -> {
            sendMessage();
        });

        String placeholder = "Escriba aquí la entrada para la consola...";
        textFieldInput.setText(placeholder);

        textFieldInput.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textFieldInput.getText().equals(placeholder)) {
                    textFieldInput.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textFieldInput.getText().isEmpty()) {
                    textFieldInput.setText(placeholder);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        consoleTextPane = new javax.swing.JTextPane();
        textFieldInput = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();

        consoleTextPane.setEditable(false);
        consoleTextPane.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(consoleTextPane);

        textFieldInput.setText(org.openide.util.NbBundle.getMessage(ConsolaTopComponent.class, "ConsolaTopComponent.textFieldInput.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sendButton, org.openide.util.NbBundle.getMessage(ConsolaTopComponent.class, "ConsolaTopComponent.sendButton.text")); // NOI18N
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cleanButton, org.openide.util.NbBundle.getMessage(ConsolaTopComponent.class, "ConsolaTopComponent.cleanButton.text")); // NOI18N
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFieldInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton)
                    .addComponent(cleanButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        sendMessage();
    }//GEN-LAST:event_sendButtonActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        consoleTextPane.setText("");
    }//GEN-LAST:event_cleanButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanButton;
    private javax.swing.JTextPane consoleTextPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField textFieldInput;
    // End of variables declaration//GEN-END:variables
@Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
        System.setIn(System.in);
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }

    public javax.swing.JTextPane getConsole() {
        return consoleTextPane;
    }

    public TextAreaInputStream getInputStream() {
        return taInputStream;
    }

    public static ConsolaTopComponent getInstance() {
        for (TopComponent tc : TopComponent.getRegistry().getOpened()) {
            if (tc instanceof ConsolaTopComponent) {
                return (ConsolaTopComponent) tc;
            }
        }
        return null;
    }

    private void sendMessage() {
        String text = textFieldInput.getText();
        taInputStream.appendText(text);
        System.out.println("> " + text);

        textFieldInput.setText("");
    }

    private void configureSmoothScroll() {
        consoleTextPane.addMouseWheelListener(new MouseWheelListener() {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                e.consume();
                JScrollPane scrollPane = (JScrollPane) SwingUtilities.getAncestorOfClass(JScrollPane.class, consoleTextPane);

                if (scrollPane != null) {
                    JScrollBar scrollBar = scrollPane.getVerticalScrollBar();

                    int pixelsToScroll = 30;
                    int currentValue = scrollBar.getValue();

                    if (e.getWheelRotation() < 0) {
                        scrollBar.setValue(currentValue - pixelsToScroll);
                    } else {
                        scrollBar.setValue(currentValue + pixelsToScroll);
                    }
                }
            }
        });
    }

    public void reconfigureForNormalMode() {
        SwingUtilities.invokeLater(() -> {
            setupNormalMode();

            // Limpiar cualquier input pendiente
            if (taInputStream != null) {
                taInputStream.clearBuffer();
            }
        });
    }

    private void setupNormalMode() {
        // Salida estándar
        TextAreaOutputStream taOutputStream = new TextAreaOutputStream(consoleTextPane, "IDE");
        PrintStream printStream = new PrintStream(taOutputStream, true, StandardCharsets.UTF_8);
        System.setOut(printStream);
        System.setErr(printStream);

        // Entrada estándar
        taInputStream = new TextAreaInputStream();
        System.setIn(taInputStream);
    }
}
